from time import sleep
from userbot import CMD_HELP, bot
from userbot.events import register
from telethon import events
import asyncio


@register(outgoing=True, pattern="^.sayang$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("I LOVEE YOUUU 💕")
        await e.edit("❤💕💞💘")
        await e.edit("❤🧡💛💙")
        await e.edit("💜💙💛💚")
        await e.edit("🖤🤍🧡❤")
        await e.edit("❤🖤🧡💛")
        await e.edit("💙🧡💚❤")
        await e.edit("SAYANG KAMU 🥺")
        await e.edit("💜💛💙💚")
        await e.edit("💞💕💗💘")
        await e.edit("❤🖤🧡💛")
        await e.edit("plisss")
        await e.edit("JANGA PERGI")
        await e.edit("SELAMANYA ❤")
        await e.edit("💘💘💘💘")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("I LOVE YOUUUU")
        await e.edit("MOREEEE 😘😘")
        await e.edit("💕💞💘💝")
        await e.edit("💘💕💞💝")
        await e.edit("BISMILLAH SLIPKOL")


@register(outgoing=True, pattern='^.tiger(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`HA HAAA.....`")
    sleep(1)
    await typew.edit("`anying ada macan gaes!!`")
    sleep(1)
    await typew.edit("`🏃                        🐅`")
    await typew.edit("`🏃                       🐅`")
    await typew.edit("`🏃                      🐅`")
    await typew.edit("`🏃                     🐅`")
    await typew.edit("`🏃   `LARII`          🐅`")
    await typew.edit("`🏃                   🐅`")
    await typew.edit("`🏃                  🐅`")
    await typew.edit("`🏃                 🐅`")
    await typew.edit("`🏃                🐅`")
    await typew.edit("`🏃               🐅`")
    await typew.edit("`🏃              🐅`")
    await typew.edit("`🏃             🐅`")
    await typew.edit("`🏃            🐅`")
    await typew.edit("`🏃           🐅`")
    await typew.edit("`🏃WOARGH!   🐅`")
    await typew.edit("`🏃           🐅`")
    await typew.edit("`🏃            🐅`")
    await typew.edit("`🏃             🐅`")
    await typew.edit("`🏃              🐅`")
    await typew.edit("`🏃               🐅`")
    await typew.edit("`🏃                🐅`")
    await typew.edit("`🏃                 🐅`")
    await typew.edit("`🏃                  🐅`")
    await typew.edit("`🏃                   🐅`")
    await typew.edit("`🏃                    🐅`")
    await typew.edit("`🏃                     🐅`")
    await typew.edit("`🏃  Huh-Huh           🐅`")
    await typew.edit("`🏃                   🐅`")
    await typew.edit("`🏃                  🐅`")
    await typew.edit("`🏃                 🐅`")
    await typew.edit("`🏃                🐅`")
    await typew.edit("`🏃               🐅`")
    await typew.edit("`🏃              🐅`")
    await typew.edit("`🏃             🐅`")
    await typew.edit("`🏃            🐅`")
    await typew.edit("`🏃           🐅`")
    await typew.edit("`🏃          🐅`")
    await typew.edit("`🏃         🐅`")
    await typew.edit("`DI MAKAN GA YAA!!!`")
    sleep(1)
    await typew.edit("`🏃       🐅`")
    await typew.edit("`🏃      🐅`")
    await typew.edit("`🏃     🐅`")
    await typew.edit("`🏃    🐅`")
    await typew.edit("`Dahlah Pasrah Aja`")
    sleep(1)
    await typew.edit("`🧎🐅`")
    sleep(2)
    await typew.edit("`-TAMAT-`")


@register(outgoing=True, pattern='^.ibuibu(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`KANG ADIT KANG ADIT.....`")
    sleep(1)
    await typew.edit("`EH ADA IBU IBU GAES!! LOH KO ILANG GOBLOK`")
    sleep(1)
    await typew.edit("`🏃                        🚶‍♀️`")
    await typew.edit("`🏃                       🚶‍♀️`")
    await typew.edit("`🏃                      🚶‍♀️`")
    await typew.edit("`🏃                     🚶‍♀️`")
    await typew.edit("`🏃   `LARII`          🚶‍♀️`")
    await typew.edit("`🏃                   🚶‍♀️`")
    await typew.edit("`🏃                  🚶‍♀️`")
    await typew.edit("`🏃                 🚶‍♀️`")
    await typew.edit("`🏃                🚶‍♀️`")
    await typew.edit("`🏃               🚶‍♀️`")
    await typew.edit("`🏃              🚶‍♀️`")
    await typew.edit("`🏃             🚶‍♀️`")
    await typew.edit("`🏃            🚶‍♀️`")
    await typew.edit("`🏃           🚶‍♀️`")
    await typew.edit("`🏃WOARGH!   🚶‍♀️`")
    await typew.edit("`🏃           🚶‍♀️`")
    await typew.edit("`🏃            🚶‍♀️`")
    await typew.edit("`🏃             🚶‍♀️`")
    await typew.edit("`🏃              🚶‍♀️`")
    await typew.edit("`🏃               🚶‍♀️`")
    await typew.edit("`🏃                🚶‍♀️`")
    await typew.edit("`🏃                 🚶‍♀️`")
    await typew.edit("`🏃                  🚶‍♀️`")
    await typew.edit("`🏃                   🚶‍♀️`")
    await typew.edit("`🏃                    🚶‍♀️`")
    await typew.edit("`🏃                     🚶‍♀️`")
    await typew.edit("`🏃  Huh-Huh           🚶‍♀️`")
    await typew.edit("`🏃                   🚶‍♀️`")
    await typew.edit("`🏃                  🚶‍♀️`")
    await typew.edit("`🏃                 🚶‍♀️`")
    await typew.edit("`🏃                🚶‍♀️`")
    await typew.edit("`🏃               🚶‍♀️`")
    await typew.edit("`🏃              🚶‍♀️`")
    await typew.edit("`🏃             🚶‍♀️`")
    await typew.edit("`🏃            🚶‍♀️`")
    await typew.edit("`🏃           🚶‍♀️`")
    await typew.edit("`🏃          🚶‍♀️`")
    await typew.edit("`🏃         🚶‍♀️`")
    await typew.edit("`BENTAR,KO KAYA EMAK GUA!!!`")
    sleep(1)
    await typew.edit("`🏃       🚶‍♀️`")
    await typew.edit("`🏃      🚶‍♀️`")
    await typew.edit("`🏃     🚶‍♀️`")
    await typew.edit("`🏃    🚶‍♀️`")
    await typew.edit("`TERNYATA EMAK GUA ANJ 😳`")
    sleep(1)
    await typew.edit("`🧎‍♂️🤺`")
    sleep(2)
    await typew.edit("`BALIK GBLK MAEN MULU`")


@register(outgoing=True, pattern="^.gabut$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`PERNAAHHHHH KAHHH KAUUU MENGIRA`")
        await e.edit("`SEPEEERTIIIII APAAAA BENTUKKKKKKK CINTAAAA`")
        await e.edit("`BENTUKNYA KAYA TAI`")
        await e.edit("`YANG DIKASIH GULALI`")
        await e.edit("`IMUUUTTTTT LUCUUU`")
        await e.edit("`WALAAUUUU TAK TERLALU TINGGI`")
        await e.edit("`TAPI MENGANU`")
        await e.edit("`EMMMM BACOTNYA`")
        await e.edit("`GABUTTTT WOI GABUT`")
        await e.edit("🙈🙈🙈🙈")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("🙈🙈🙈🙈")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("`CILUUUKKK BAAAAA`")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("🧎‍♂️                       🚶")
        await e.edit("🧎‍♂️                      🚶")
        await e.edit("🧎‍♂️                     🚶")
        await e.edit("🧎‍♂️                    🚶")
        await e.edit("🧎‍♂️                   🚶")
        await e.edit("🧎‍♂️                  🚶")
        await e.edit("🧎‍♂️                 🚶")
        await e.edit("🧎‍♂️                🚶")
        await e.edit("🧎‍♂️               🚶")
        await e.edit("🧎‍♂️              🚶")
        await e.edit("🧎‍♂️             🚶")
        await e.edit("🧎‍♂️            🚶")
        await e.edit("🧎‍♂️           🚶")
        await e.edit("🧎‍♂️          🚶")
        await e.edit("🧎‍♂️         🚶")
        await e.edit("🧎‍♂️        🚶")
        await e.edit("🧎‍♂️       🚶")
        await e.edit("🧎‍♂️      🚶")
        await e.edit("🧎‍♂️     🚶")
        await e.edit("🧎‍♂️    🚶")
        await e.edit("🧎‍♂️   🚶")
        await e.edit("🧎‍♂️  🚶")
        await e.edit("🧎‍♂️ 🚶")
        await e.edit("BERUBAH 🚶")
        await e.edit("🚶🤺")
        await e.edit("🚶 🤺")
        await e.edit("🚶  🤺")
        await e.edit("🚶   🤺")
        await e.edit("🚶    🤺")
        await e.edit("🚶     🤺")
        await e.edit("🚶      🤺")
        await e.edit("🚶       🤺")
        await e.edit("🚶        🤺")
        await e.edit("🚶         🤺")
        await e.edit("🚶          🤺")
        await e.edit("🚶           🤺")
        await e.edit("🚶            🤺")
        await e.edit("🚶             🤺")
        await e.edit("🚶              🤺")
        await e.edit("🚶               🤺")
        await e.edit("🚶                🤺")
        await e.edit("🚶                 🤺")
        await e.edit("🚶                  🤺")
        await e.edit("🚶                   🤺")
        await e.edit("🚶                    🤺")
        await e.edit("🚶                     🤺")
        await e.edit("🚶                      🤺")
        await e.edit("🚶                       🤺")
        await e.edit("🚶                        🤺")
        await e.edit("🚶                         🤺")
        await e.edit("🚶                          🤺")
        await e.edit("🚶                           🤺")
        await e.edit("🚶                            🤺")
        await e.edit("🚶   Cape                      💃")
        await e.edit("🚶                              💃")
        await e.edit("🚶                               💃")
        await e.edit("🚶                                💃")
        await e.edit("🚶                                 💃")
        await e.edit("`AHHH MANTAP`")
        await e.edit("🙉")
        await e.edit("🙈")
        await e.edit("🙉")
        await e.edit("🙈")
        await e.edit("🙉")
        await e.edit("😂")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("`GABUT`")


@register(outgoing=True, pattern='^.terkadang(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Terkadang`")
    sleep(1)
    await typew.edit("`Mencintai Seseorang`")
    sleep(1)
    await typew.edit("`Hanya Akan Membuang Waktumu`")
    sleep(1)
    await typew.edit("`Ketika Waktumu Habis`")
    sleep(1)
    await typew.edit("`Gua jual nih goceng`")
    sleep(1)
    await typew.edit("`Bercanda`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.mf$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`mf g dl` **ミ(ノ;_ _)ノ=3** ")


@bot.on(events.NewMessage(pattern=r"\.(.*)", outgoing=True))
async def _(event):

    if event.fwd_from:

        return

    animation_interval = 2

    animation_ttl = range(0, 11)

    input_str = event.pattern_match.group(1)

    if input_str == "cinta":

        await event.edit(input_str)

        animation_chars = [
            "`Loading To Your Heart`",
            "`Mencari Hati mu`",
            "`Mengirim Cintaku.. 0%\n▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 4%\n█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 8%\n██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 20%\n█████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 36%\n█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 52%\n█████████████▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 84%\n█████████████████████▒▒▒▒ `",
            "`Mengirim Cintaku.. 100%\n██████████BERHASIL██████████ `",
            f"`Berhasil Masuk ke hatimu dan Sekarang aku sangat mencintaimu, I Love You 😘 Bismillah slipkol 😢`"]

        for i in animation_ttl:

            await asyncio.sleep(animation_interval)

            await event.edit(animation_chars[i % 11])


@register(outgoing=True, pattern='^.gombal(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Hai, I LOVE YOU 💞`")
    sleep(1)
    await typew.edit("`I LOVE YOU SO MUCH!`")
    sleep(1)
    await typew.edit("`I NEED YOU!`")
    sleep(1)
    await typew.edit("`I WANT TO BE YOUR BOYFRIEND!`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💕💗`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💗💞`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💝💗`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💟💖`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💘💓`")
    sleep(1)
    await typew.edit("`SERIUSAN KO..NIKAH YUK`")
# Create by myself @localheart

CMD_HELP.update({
    "gabut":
    "`.gabut` ; `.dino`.tiger`\
    \nUsage: ntahlah gabut doang.\
    \n\n`.gombal`\
    \nUsage: buat bercanda\
    \n\n`.cinta`\
    \nUsage: mengirim cintamu ke seseorang.\
    \n\n`.sayang`\
    \nUsage: untuk jadi buaya.\
    \n\n`.terkadang`\
    \nUsage: Auk dah iseng doang."
})
